# Makefile for the focaltech touchscreen drivers.
obj-$(CONFIG_TOUCHSCREEN_FT3658U_I2C)	+=  focaltech_core.o
obj-$(CONFIG_TOUCHSCREEN_FT3658U_I2C)	+=  focaltech_ex_fun.o
obj-$(CONFIG_TOUCHSCREEN_FT3658U_I2C)	+=  focaltech_ex_mode.o
obj-$(CONFIG_TOUCHSCREEN_FT3658U_I2C)	+=  focaltech_gesture.o
obj-$(CONFIG_TOUCHSCREEN_FT3658U_I2C)	+=  focaltech_esdcheck.o
obj-$(CONFIG_TOUCHSCREEN_FT3658U_I2C)   +=  focaltech_point_report_check.o
obj-$(CONFIG_TOUCHSCREEN_FT3658U_I2C)	+=  focaltech_flash.o
obj-$(CONFIG_TOUCHSCREEN_FT3658U_I2C)   +=  focaltech_flash/focaltech_upgrade_ft3658u.o
obj-$(CONFIG_TOUCHSCREEN_FT3658U_I2C)   +=  focaltech_i2c.o
